; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+x -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=RV64IFDX %s

; Function Attrs: nounwind
declare i64 @llvm.hwacha.veidx()

; Function Attrs: noinline nounwind
define dso_local i64 @_pocl_launcher_saxpy(i64, float*, float*, float) {
; RV64IFDX-LABEL: _pocl_launcher_saxpy:
; RV64IFDX:       # %bb.0: # %body
; RV64IFDX-NEXT:    vpset vp0
; RV64IFDX-NEXT:    @vp0 vlw vv0, va1
; RV64IFDX-NEXT:    @vp0 vfmul.s vv0, vv0, vs4
; RV64IFDX-NEXT:    @vp0 vlw vv1, va2
; RV64IFDX-NEXT:    @vp0 vfadd.s vv0, vv1, vv0
; RV64IFDX-NEXT:    @vp0 vsw vv0, va2
; RV64IFDX-NEXT:    vstop
body:
  %idx = call i64 @llvm.hwacha.veidx()
  %arrayidx.i = getelementptr float, float* %1, i64 %idx
  %tomul = load float, float* %arrayidx.i, align 4
  %mul.i = fmul float %tomul, %3

  %arrayidx2.i = getelementptr float, float* %2, i64 %idx
  %toadd = load float, float* %arrayidx2.i, align 4
  %add.i = fadd float %toadd, %mul.i
  store float %add.i, float* %arrayidx2.i, align 4
  %vlret = call i64 @llvm.hwacha.vretvl(i64 %0)
  ret i64 %vlret
}

define dso_local i64 @_pocl_launcher_saxpy_workgroup(float*, float*, float) {
; RV64IFDX-LABEL: _pocl_launcher_saxpy_workgroup:
; RV64IFDX:       # %bb.0:
; RV64IFDX-NEXT:    addi sp, sp, -16
; RV64IFDX-NEXT:    sd s0, 8(sp)
; RV64IFDX-NEXT:    addi a3, zero, 1234
; RV64IFDX-NEXT:    vmcs vs1,a3
; RV64IFDX-NEXT:    vmcs vs4,a2
; RV64IFDX-NEXT:    vmca va1,a0
; RV64IFDX-NEXT:    vmca va2,a1
; RV64IFDX-NEXT:    vsetcfg a0,0,2,0,1
; RV64IFDX-NEXT:    vsetvl s0,a3
; RV64IFDX-NEXT:    la a0, _pocl_launcher_saxpy
; RV64IFDX-NEXT:    vf 0(a0)
; RV64IFDX-NEXT:    mv a0, s0
; RV64IFDX-NEXT:    ld s0, 8(sp)
; RV64IFDX-NEXT:    addi sp, sp, 16
; RV64IFDX-NEXT:    ret
  %vl = add i64 0, 1234
  %newvl = call i64 @_pocl_launcher_saxpy(i64 %vl, float* %0, float* %1, float %2)
  ret i64 %newvl
}

!opencl.kernels = !{!2}
declare i64 @llvm.hwacha.vretvl(i64)


!2 = !{i64 (i64, float*, float*, float)* @_pocl_launcher_saxpy}
