; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I
; RUN: llc -mtriple=riscv32 -mattr=+c -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32C

define void @foo() {
; RV32I-LABEL: foo:
; RV32I:       # %bb.0: # %entry
; RV32I-NEXT:    ret
;
; RV32C-LABEL: foo:
; RV32C:       # %bb.0: # %entry
; RV32C-NEXT:    ret
entry:
  ret void
}
